---
- name: Site setup
  hosts:
    # - dba-art-kite-crow.gc.com
    - localhost
  # connection: local
  vars_prompt:
    - name: "configure_zsh"
      prompt: "Do you want to configure zsh with some recommended dotfiles? (yes/no)"
      private: false
      default: "no"
  gather_facts: true
  vars:
    venv_dir: "{{ ansible_env.HOME }}/.pipx" # $HOME/.pipx
    pipx: "{{ venv_dir }}/bin/pipx"
  roles:
    # - dotfiles
    # - fonts
    # - workstation
    # - workstation-platform
    - dev
  
    # - remote
    # - dev-personal
