---
- name: Site setup
  hosts:
    # - dba-art-kite-crow.gc.com
    - localhost
  # connection: local
  gather_facts: yes
  vars:
    venv_dir: "{{ ansible_env.HOME }}/.pipx" # $HOME/.pipx
    pipx: "{{ venv_dir }}/bin/pipx"
  roles:
    - workstation
    # - fonts
    # - remote
    # - dev
    # - dev-personal
