---
# TODO: clone my dotfiles into the home directory
- name: Install Self Selected Dev Packages
  package:
    name:
      - neovim # better vim
      - tldr
      - thefuck # fix terminal mistakes
      - tmux # terminal multiplexing
    state: present
  become: yes

- import_tasks: btop.yml
- import_tasks: shfmt.yml

# lua-language-server
