---
- name: GameChanger Corporate Software for MacOS
  when: ansible_distribution == 'MacOSX'
  block:
    - name: Install Homebrew package manager
      ansible.builtin.import_tasks: homebrew.yml

    - name: Install the macOS amd64 translator
      ansible.builtin.import_tasks: rosetta2.yml

    - name: Install my apps
      ansible.builtin.import_tasks: personal.yml
