---
# NOTE: `homebrew_cask` is a required hack.
#       packages will default to homebrew which will report failure for
#       existing software
- name: Install/Upgrade Casks for Self Selected Software
  homebrew_cask:
    name:
      - alacritty
      - bartender
      - obs # media recorder
      - yubico-yubikey-manager
      - firefox
      - iina # media player
      - topnotch
      - alfred
    state: latest

- name: Install Self Selected Software
  homebrew:
    name:
      - gnupg
      - ykman # yubikey
      - reattach-to-user-namespace # tmux requirement on MacOS
    state: latest

- name: Install/Upgrade Entertainment Software
  homebrew_cask:
    name:
      - signal
    state: latest



# brew install koekeishiya/formulae/skhd
# brew install koekeishiya/formulae/yabai
# - hosts: localhost
#   tasks:
#     - name: Install yabai and skhd via Homebrew
#       homebrew:
#         name:
#           - koekeishiya/formulae/yabai
#           - koekeishiya/formulae/skhd
#         state: present
