---
# NOTE: `homebrew_cask` is a required hack.
#       packages will default to homebrew which will report failure for
#       existing software
- name: Install/Update Apps
  community.general.homebrew_cask:
    name:
      # - 1password
      - alacritty
      - alfred
      - bartender
      - topnotch
      - yubico-yubikey-manager
      # - obs # media recorder
      # - iina # media player
    state: latest
    accept_external_apps: true

- name: Install/Update Programs
  community.general.homebrew:
    name:
      - gnupg
      - reattach-to-user-namespace # tmux requirement on MacOS
      - ykman # yubikey
      - zsh
    state: latest
# brew install koekeishiya/formulae/skhd
# brew install koekeishiya/formulae/yabai
# - hosts: localhost
#   tasks:
#     - name: Install yabai and skhd via Homebrew
#       homebrew:
#         name:
#           - koekeishiya/formulae/yabai
#           - koekeishiya/formulae/skhd
#         state: present
