---
- name: Install Foundations-Suggested CLI Packages
  package:
    name:
      - less
      - source-highlight # used by less with default highlight
    state: latest
  become: yes

# - name: Add fd deb repository
#   ansible.builtin.apt_repository:
#     repo: 'deb http://httpredir.debian.org/debian buster main'
#     state: present
#   become: true

# - name: Add specified repository into sources list
#   ansible.builtin.apt_repository:
#     repo: deb http://archive.canonical.com/ubuntu hardy partner
#     state: present
# https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-musl_8.7.0_amd64.deb
# TODO: can I add a mirror?
# - name: Install deb packages
#   apt:
#     deb: "{{ item }}"
#   with_items: "{{ deb_packages }}"

- name: Install 🦀 packages
  become: yes
  block:
  - name: Install "fd" 🦀 package
    apt:
      deb: https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-musl_8.7.0_amd64.deb

  - name: Install "lsd" 🦀 package
    apt:
      deb: https://github.com/lsd-rs/lsd/releases/download/0.23.1/lsd-musl_0.23.1_amd64.deb
    
  - name: Install "bat" 🦀 package
    apt:
      deb: https://github.com/sharkdp/bat/releases/download/v0.23.0/bat-musl_0.23.0_amd64.deb

  - name: Install "delta" 🦀 package
    apt:
      deb: https://github.com/dandavison/delta/releases/download/0.16.5/git-delta-musl_0.16.5_amd64.deb

  # - name: Force Rescue
  #   debug:
  #     msg: "Force rescue block activated..."
  #   failed_when: true

  rescue:
  - name: Remove package with apt
    apt:
      name: "{{ item }}"
      state: absent
    with_items:
      - fd-musl
      - lsd-musl
      - bat-musl
      - git-delta-musl
