---
- name: Set distro-specific variables
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_os_family | lower }}.yml'
    - main.yml

# - import_tasks: rust.yml
# - import_tasks: starship.yml
- import_tasks: rc.yml
# - import_tasks: darwin.yml
#   when: ansible_distribution == 'MacOSX'
- import_tasks: debian.yml
  when: ansible_os_family == 'Debian'
