---
- name: Install Foundations-Suggested Dev Packages
  package:
    name:
      # - bash # required for eden?
      - git # version control
      - git-lfs # git large files
      - make
      - jq
      - npm
      - colordiff
    state: latest
  become: yes

# Not every venv edition creates a pip binary
- name: Check if virtual environment already exists
  stat:
    path: "{{ venv_dir }}"
  register: venv_stat

- name: Create a virtual environment
  command: python3 -m venv "{{ venv_dir }}"
  when: not venv_stat.stat.exists

- name: Upgrade pip in the virtual environment
  command: "{{ venv_dir }}/bin/python -m pip install --upgrade pip"
  when: not venv_stat.stat.exists

- name: Install pipx
  pip:
    name: pipx
    state: present
    executable: "{{ venv_dir }}/bin/pip"

# - name: Install AWS CLI
#   community.general.pipx:
#     name: awscliv2
#     state: present
#     executable: "{{ pipx }}"
# TODO: must run awsv2 --install?
- name: Install pre-commit
  community.general.pipx:
    name: pre-commit
    state: present
    executable: "{{ pipx }}"

# TODO: update gcaws to support python3.8
- name: Install gcaws (GameChanger AWS CLI helper)
  community.general.pipx:
    name: gcaws==0.26
    state: present
    index_url: https://pypi.gamechanger.io/simple/
    executable: "{{ pipx }}"
