- name: Set fonts directory fact.
  ansible.builtin.set_fact:
    nf_fonts_dir: "{{ (ansible_facts['os_family'] == 'Darwin') | ternary(nf_macos_fonts_dir, nf_linux_fonts_dir) }}"

- name: Ensure fonts directory exists.
  ansible.builtin.file:
    path: "{{ nf_fonts_dir }}"
    recurse: true
    state: directory

- name: Download HackNerdFont ttf files to {{ nf_fonts_dir }}
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nf_fonts_dir }}/"
    group: "{{ ansible_user_gid | default(omit) }}"
    owner: "{{ ansible_user_id }}"
    mode: "0644"
    force: false
  with_items: "{{ nf_single_fonts }}"

# - name: Download individual fonts to fonts directory.
#   ansible.builtin.include_tasks: "download_font.yml"
#   loop: "{{ nf_single_fonts }}"
#   loop_control:
#     loop_var: font
